### PR TITLE
Add fs-button blue as a css variable

### PR DESCRIPTION
**Pull request by dcravenus**
I noticed fs-button blue was missing as a css variable. I don't know how to test this or anything but I noticed $blue seems to be defined, just not as a CSS variable.

### CODE REVIEW

**Comment by dcravenus** [comment]
Where `$blue` is defined:
https://github.com/fs-webdev/fs-styles/blob/cfa955144b723ce1766e5179548597b588aa9516/assets/css/elements/_buttons.styl#L28

**Comment by justincy** [comment]
Can you bump the version?

**Comment by dcravenus** [comment]
yessir

**Comment by justincy** [comment]
We just did a 5.1.0 release of fs-styles so I changed this to 5.1.1. I also ran the build to update files in `dist`.

**Pull request merged**
