### PR TITLE
OFT-70150. Adds better font support for Thai.

### PR DESCRIPTION
**Pull request by crowtherdr**
The Windows system fonts provide valid Thai font support. However, the Mac fallback system font (Thonburi) does not have all of the correct characters for Thai. Ayuthaya is one of four Mac system fonts that provide a correct set of Thai characters. I prefer the Ayuthaya font and Mark G & Ryan P agreed. If the style guide council chooses one of the other fonts, that is ok with me. The other fonts are Krungthep, Sathu, and Silom. Mark & Ryan definitely did not like Krungthep. Examples of these fonts are in comments by Tyler P in the JIRA (OFT-70150)

This does not correct the problem for iOS.

Examples from Tree
Before:
image

After:
image

Changes are also being made to Tree v8 components to not ovrerride the fs-styles font definitions.
- https://github.com/fs-webdev/tree/pull/1077
- https://github.com/fs-webdev/fs-couple-renderer/pull/15
- https://github.com/fs-webdev/fs-person-card/pull/125

### CODE REVIEW

**Comment by timothydm42** [comment]
@crowtherdr Looks good to me. May we pull the trigger on this, or should I confirm at the next styleguide council meeting?

**Comment by crowtherdr** [comment]
I think that the only thing to confirm with the council is the choice of font. I thought @jeffreythawkins add this as an agenda item for the last styleguide council meeting (12 Jun). Was it not discussed? I know that Jeff was not there, but I thought Ryan was aware of the issue.

**Comment by timothydm42** [comment]
@crowtherdr I was absent as well. I'll ask Ryan

**Comment by crowtherdr** [comment]
There were conflicts with master in the 3 files that are built by `gulp build`. I merged master into my fork, ran `gulp build`, marked the conflicts as resolved, and then committed and pushed the changes.

**Comment by crowtherdr** [comment]
I just sent an email reminder about this and included @timothydm42 as a recipient.

**Comment by timothydm42** [comment]
@crowtherdr would you please update this branch and increment the minor version? Thank you!

We're ready to merge it in

**Comment by crowtherdr** [comment]
Ok, @timothydm42, I think I updated to what you wanted.

**Pull request merged**
