### PR TITLE
Display Verdana in headings instead of Ayuthaya while waiting for museo to load

### PR DESCRIPTION
**Pull request by justincy**
This fixes a bug where Chrome shows the Ayuthaya font while waiting for Museo to load. 

First no text is shown. Chrome gives Museo 3s to load. After waiting for 3s Chrome uses the fallback which is the next font in line. Museo is later displayed once it's finally loaded. So we have three phases: nothing -> Ayuthaya -> Museo.

The styleguide council caught this and requested that we show Verdana instead which is easily done by adding it to the stack before Ayuthaya.

### CODE REVIEW

**Comment by justincy** [comment]
@timothydm42 Are you okay with a merge and release as 5.0.4?

**Comment by timothydm42** [comment]
most definitely

**Comment by justincy** [comment]
Looks like I can't merge; waiting on approval by someone with write permissions.

**Comment by timothydm42** [comment]
huh ok i'll do it

**Pull request merged**
