### PR TITLE
alert vars and docs

### PR DESCRIPTION
**Pull request by timothydm42**

### CODE REVIEW

**Comment by liechtym** [comment]
Did you apply the variables anywhere? That's usually when it would need to compile. I don't think it has to compile anything when just declaring variables. Only stylus uses those vars, they are not carried in any way to the CSS besides their values being printed where they are used

**Comment by timothydm42** [comment]
Ok, I'll use those vars in the alerts file

**Comment by timothydm42** [comment]
Ok. So the _alerts.styl is using the variables now, and since those variables' values are the same as the values already in the CSS, there is no need to change those files. correct?

**Comment by timothydm42** [comment]
oh. and I need to add the new alert color vars manually to familysearch-styles.styl I take it

**Comment by timothydm42** [comment]
cool that last put the vars as CSS vars in CSS files

**Pull request merged**
