### PR TITLE
Move from :checked to [checked] because the meta attribute is not updated reliably when manipulating a checkbox element directly

### PR DESCRIPTION
**Pull request by dthorne**
In global dialogs like fs-add-person and fs-tree-conclusion when we reset the property/attribute of a checkbox via Polymer or vanilla. The styles don't update to show the correct checked value. They are only updated by user input. This is especially confusing because the "checked" attribute is true but the styling isn't matching so you could proceed with the wrong value because the UI and the DOM state don't match. 

I have tested this change with fs-tree-conclusion and it fixes the issue because it uses DOM state to determine if it should show as checked.

Let me know if you have questions.

### CODE REVIEW

**Comment by dthorne** [comment]
@tylergraf Do you think this is significant enought that we should run it by other teams and get more buy-off? I've tested it but it might be worth trying it in a couple more places to ensure that it doesn't break anything.

**Comment by tylergraf** [comment]
Yeah, I think we should. You have to make sure that you set the `checked` attribute. A non-breaking way to change it would be to add `[checked]` instead of changing `:checked` in the css.

**Comment by dthorne** [comment]
Well, That causes the false one and real one to be checked
Unless we make the `[checked]` one override it which I'm not excited about.

**Comment by tylergraf** [comment]
Yeah, that seems kinda gross, but also safe.

**Comment by timothydm42** [comment]
It looks to me like our choices are: 

a) merge this as breaking, have teams do the work to update
b) do the `[checked]` override thing; home team makes the story and gets it in an iteration, does work, merge it as patch

is that right?

I'm leaning toward (b) what say you?

**Comment by dthorne** [comment]
I'm fine with the override this especially if you guys are doing the work.

**Comment by dthorne** [comment]
@timothydm42 Is there work in progress to fix this? What action needs to be taken?

**Comment by timothydm42** [comment]
thanks @dthorne. 

I have found some issues with this. currently, the checked attribute is only used to set initial dom state and is ignored thereafter.

that being the case, the override solution ends up being a breaking change, since the current behavior is for the attribute not to matter beyond page load: in many instances the checked attribute is used just to set the default state to checked, but is never unset programatically. User interaction doesn't change the attribute either, only the property. 

Also I have a question just to be sure: in `fs-tree-conclusion`, have you tried omitting the `$` as in `checked=[[thing]]` NOT `checked$=[[thing]]`  ?

**Comment by dthorne** [comment]
@skye2k2 Have we tried the solution proposed directly above?

**Comment by rosemariesadler** [comment]
getting rid of the $= and changing it to a normal = does seem to fix the problem for fs-tree-conclusion. I think though that long term, we just need to move any web components using checkboxes and radio buttons to fs-checkbox and fs-radiobutton because with polymer bindings, it's unpredictable what will work where. 

The real problem is that in the dom spec, the checked attribute and checked property are distinct and mean different things, so as developers, using the checked attribute in a binding is the "wrong" thing to do. That is why fs-checkbox/fs-radiobutton is the "right" thing to do because then it will only manage the checked property for us and won't touch the checked attribute on the actual input.

**Pull request closed without merging**
